/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2026-05-07 17:54:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class addFinance_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

    if (session.getAttribute("role") == null || !"User".equals(session.getAttribute("role"))) {
        response.sendRedirect("login.jsp");
        return;
    }

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>Add Finance - Finance Management</title>\n");
      out.write("    <link rel=\"stylesheet\" href=\"style.css\">\n");
      out.write("    <style>\n");
      out.write("        select {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            background: rgba(15, 23, 42, 0.6);\n");
      out.write("            border: 1px solid var(--border-color);\n");
      out.write("            border-radius: 8px;\n");
      out.write("            color: var(--text-main);\n");
      out.write("            font-size: 1rem;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("        select:focus {\n");
      out.write("            outline: none;\n");
      out.write("            border-color: var(--primary-color);\n");
      out.write("        }\n");
      out.write("        input[type=\"date\"] {\n");
      out.write("            width: 100%;\n");
      out.write("            padding: 0.75rem 1rem;\n");
      out.write("            background: rgba(15, 23, 42, 0.6);\n");
      out.write("            border: 1px solid var(--border-color);\n");
      out.write("            border-radius: 8px;\n");
      out.write("            color: var(--text-main);\n");
      out.write("            font-size: 1rem;\n");
      out.write("            transition: all 0.3s ease;\n");
      out.write("        }\n");
      out.write("    </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container login-container\" style=\"max-width: 500px;\">\n");
      out.write("        <div class=\"header-actions\" style=\"margin-bottom: 1.5rem; padding-bottom: 0.5rem;\">\n");
      out.write("            <h2 style=\"margin-bottom: 0;\">Add Finance Record</h2>\n");
      out.write("            <a href=\"user.jsp\" class=\"btn btn-outline\" style=\"padding: 0.5rem 1rem; font-size: 0.875rem;\">&larr; Back</a>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        ");
 
            String error = request.getParameter("error");
            if (error != null) {
                String msg = "";
                if (error.equals("insert_failed")) msg = "Failed to add record. Please try again.";
                else if (error.equals("exception")) msg = "System error occurred.";
                out.println("<div class='alert alert-error'>" + msg + "</div>");
            }
        
      out.write("\n");
      out.write("\n");
      out.write("        <form action=\"AddFinanceServlet\" method=\"post\">\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"type\">Record Type</label>\n");
      out.write("                <select id=\"type\" name=\"type\" required>\n");
      out.write("                    <option value=\"\" disabled selected>Select Type</option>\n");
      out.write("                    <option value=\"Income\">Income</option>\n");
      out.write("                    <option value=\"Expense\">Expense</option>\n");
      out.write("                    <option value=\"Investment\">Investment</option>\n");
      out.write("                </select>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"amount\">Amount ($)</label>\n");
      out.write("                <input type=\"number\" step=\"0.01\" min=\"0\" id=\"amount\" name=\"amount\" required placeholder=\"0.00\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"description\">Description</label>\n");
      out.write("                <input type=\"text\" id=\"description\" name=\"description\" required placeholder=\"e.g. Office Supplies, Travel Expense\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("                <label for=\"date\">Date</label>\n");
      out.write("                <input type=\"date\" id=\"date\" name=\"date\" required>\n");
      out.write("            </div>\n");
      out.write("            <button type=\"submit\" class=\"btn\">Submit Record</button>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
